# -
017-11-21 17:24:02> Program: Starting Squirrel Updater: --install . 2017-11-21 17:24:02> Program: Starting install, writing to C:\Users\Administrator\AppData\Local\SquirrelTemp 2017-11-21 17:24:02> Program: About to install to: C:\Users\Administrator\AppData\Local\GitHubDesktop 2017-11-21 17:24:03> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\GitHubDesktop\packages\.betaId'.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)    at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)    at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)    at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)    at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId() 2017-11-21 17:24:03> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\GitHubDesktop\packages\RELEASES'.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)    at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)    at Squirrel.UpdateManager.CheckForUpdateImpl.&lt;CheckForUpdate>d__2.MoveNext() 2017-11-21 17:24:03> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Administrator\AppData\Local\SquirrelTemp 2017-11-21 17:24:03> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch 2017-11-21 17:24:03> ApplyReleasesImpl: Writing files to app directory: C:\Users\Administrator\AppData\Local\GitHubDesktop\app-1.0.9 2017-11-21 17:24:03> LogHost: Rigging execution stub for lib/net45/GitHubDesktop_ExecutionStub.exe to C:\Users\Administrator\AppData\Local\GitHubDesktop\GitHubDesktop.exe 2017-11-21 17:24:07> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Administrator\AppData\Local\GitHubDesktop\app-1.0.9\GitHubDesktop.exe] 2017-11-21 17:24:18> ApplyReleasesImpl: Starting fixPinnedExecutables 2017-11-21 17:24:18> ApplyReleasesImpl: Fixing up tray icons 2017-11-21 17:24:18> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.    at Squirrel.UpdateManager.ApplyReleasesImpl.&lt;unshimOurselves>b__13_0(RegistryView view) 2017-11-21 17:24:18> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.    at Squirrel.UpdateManager.ApplyReleasesImpl.&lt;unshimOurselves>b__13_0(RegistryView view) 2017-11-21 17:24:18> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9 2017-11-21 17:24:18> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.9 2017-11-21 17:42:27> Program: Starting Squirrel Updater: --install . 2017-11-21 17:42:27> Program: Starting install, writing to C:\Users\Administrator\AppData\Local\SquirrelTemp 2017-11-21 17:42:27> Program: About to install to: C:\Users\Administrator\AppData\Local\GitHubDesktop 2017-11-21 17:42:27> Program: Install path C:\Users\Administrator\AppData\Local\GitHubDesktop already exists, burning it to the ground 2017-11-21 17:42:28> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: The process cannot access the file 'C:\Users\Administrator\AppData\Local\GitHubDesktop\packages\GitHubDesktop-1.0.9-full.nupkg' because it is being used by another process.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at System.IO.File.InternalDelete(String path, Boolean checkHost)    at System.IO.File.Delete(String path)    at Squirrel.Utility.&lt;>c.&lt;DeleteDirectory>b__19_0(String file)    at Squirrel.Utility.&lt;>c__DisplayClass12_1`1.&lt;ForEachAsync>b__1()    at System.Threading.Tasks.Task.InnerInvoke()    at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;>c__DisplayClass13_0`1.&lt;&lt;ForEachAsync>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;DeleteDirectory>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;>c.&lt;&lt;DeleteDirectory>b__19_1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;>c__DisplayClass13_0`1.&lt;&lt;ForEachAsync>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;DeleteDirectory>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;LogIfThrows>d__37.MoveNext() 2017-11-21 17:42:28> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Administrator\AppData\Local\GitHubDesktop\packages\GitHubDesktop-1.0.9-full.nupkg' because it is being used by another process.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at System.IO.File.InternalDelete(String path, Boolean checkHost)    at System.IO.File.Delete(String path)    at Squirrel.Utility.&lt;>c.&lt;DeleteDirectory>b__19_0(String file)    at Squirrel.Utility.&lt;>c__DisplayClass12_1`1.&lt;ForEachAsync>b__1()    at System.Threading.Tasks.Task.InnerInvoke()    at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;>c__DisplayClass13_0`1.&lt;&lt;ForEachAsync>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;DeleteDirectory>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;>c.&lt;&lt;DeleteDirectory>b__19_1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;>c__DisplayClass13_0`1.&lt;&lt;ForEachAsync>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;DeleteDirectory>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;LogIfThrows>d__37.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Squirrel.Update.Program.&lt;Install>d__4.MoveNext()    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)    at System.Threading.Tasks.Task.Wait()    at Squirrel.Update.Program.executeCommandLine(String[] args)    at Squirrel.Update.Program.main(String[] args) ---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\Administrator\AppData\Local\GitHubDesktop\packages\GitHubDesktop-1.0.9-full.nupkg' because it is being used by another process.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at System.IO.File.InternalDelete(String path, Boolean checkHost)    at System.IO.File.Delete(String path)    at Squirrel.Utility.&lt;>c.&lt;DeleteDirectory>b__19_0(String file)    at Squirrel.Utility.&lt;>c__DisplayClass12_1`1.&lt;ForEachAsync>b__1()    at System.Threading.Tasks.Task.InnerInvoke()    at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;>c__DisplayClass13_0`1.&lt;&lt;ForEachAsync>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;DeleteDirectory>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;>c.&lt;&lt;DeleteDirectory>b__19_1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;>c__DisplayClass13_0`1.&lt;&lt;ForEachAsync>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;DeleteDirectory>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Squirrel.Utility.&lt;LogIfThrows>d__37.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Squirrel.Update.Program.&lt;Install>d__4.MoveNext()&lt;---
